language: java

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e581add5f7f207b5248a
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
